<?xml version='1.0'?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find my_robot)/urdf/extra/materials.xacro" />
  <xacro:include filename="$(find my_robot)/urdf/my_robot.gazebo" />
  <xacro:include filename="$(find my_robot)/urdf/extra/camera_holder.urdf.xacro" />

  <!--
  #################################################
        Global Properties
  #################################################
  -->

  <xacro:property name="holder_rod_r"   value="0.02" />
  <xacro:property name="holder_rod_l"   value="0.1" />
  <xacro:property name="holder_plate_w" value="0.1" />
  <xacro:property name="holder_plate_l" value="0.3" />
  <xacro:property name="holder_plate_h" value="0.02" />
  
  <xacro:property name="chassis_h" value="0.1" />
  <xacro:property name="chassis_r" value="0.22" />
  <xacro:property name="top_module_r" value="0.15" />
  <xacro:property name="top_module_h" value="0.1" />
  
  <xacro:property name="camera_w" value="0.03" />
  <xacro:property name="camera_l" value="0.15" />
  <xacro:property name="camera_h" value="0.05" />

  <xacro:property name="hokuyo_pos_xyz" value="0.24 0.0 0.05" />
  <xacro:property name="hokuyo_pos_rpy" value="0.0 0.0 0.0" />
  
  <xacro:property name="camera_pos_xyz" value="0.0 0.0 ${camera_h/2 + holder_rod_l/2 + holder_plate_h}" />
  <xacro:property name="camera_pos_rpy" value="0.0 0.0 0.0" />
  
  <!--
  #################################################
        Joint Declaration
  #################################################
  -->
    
  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>
  
  <joint type="continuous" name="left_wheel_hinge">
    <origin xyz="0 0.15 -0.05" rpy="0 1.5707 1.5707"/>
    <child link="left_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 0 1" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>
  
  <joint type="continuous" name="right_wheel_hinge">
    <origin xyz="0 -0.15 -0.05" rpy="0 1.5707 1.5707"/>
    <child link="right_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 0 1" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>
  
  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="${hokuyo_pos_xyz}" rpy="${hokuyo_pos_rpy}"/>
    <child link="hokuyo"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

  <!--
  #################################################
        Joints = camera_holder & camera
  #################################################
  -->
  
  <xacro:property name="holder_rod_1_xyz"   value="0.0 0.1 0.0" />
  <xacro:property name="holder_rod_2_xyz"   value="0.0 -0.1 0.0" />
  <xacro:property name="holder_plate_xyz"   value="0.0 0.0 ${holder_rod_l/2 + holder_plate_h/2}" />
  
  <xacro:camera_holder
      name="camera_holder"
      parent="chassis"
      origin_xyz="0 0 ${chassis_h + 0.1}"
      origin_rpy="0 0 0"
      />
  
  <joint type="fixed" name="camera_joint">
    <origin xyz="${camera_pos_xyz}" rpy="${camera_pos_rpy}"/>
    <child link="rgbd_camera_link"/>
    <parent link="camera_holder_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

  <joint type="fixed" name="camera_optical_joint">
      <origin xyz="0 0 0" rpy="-1.5707 0 -1.5707" />
      <parent link="rgbd_camera_link" />
      <child link="camera_link_optical" />
  </joint>
  
  
  <!--
  #################################################
        link = robot_footprint
  #################################################
  -->

  <link name="robot_footprint"></link>
  
  <!--
  #################################################
        link = chassis
  #################################################
  -->
  
  <link name='chassis'>
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="15.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <!-- Part 1 -->

    <collision name='chassis_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <cylinder radius="${chassis_r}" length="${chassis_h}" />
      </geometry>
    </collision>

    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <cylinder radius="${chassis_r}" length="${chassis_h}" />
      </geometry>
    </visual>

    <!-- Part 2 
         For this base, the casters are included as part of the link for stability.
    -->

    <collision name='back_caster_collision'>
      <origin xyz="-0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="0.0499"/>
      </geometry>
    </collision>

    <visual name='back_caster_visual'>
      <origin xyz="-0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </visual>

    <!-- Part 3
         For this base, the casters are included as part of the link for stability.
    -->
    
    <collision name='front_caster_collision'>
      <origin xyz="0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="0.0499"/>
      </geometry>
    </collision>

    <visual name='front_caster_visual'>
      <origin xyz="0.15 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </visual>
    
    <collision name='top_plate_collision'>
      <origin xyz="0.0 0 0.1" rpy=" 0 0 0"/>
      <geometry>
        <cylinder radius="${top_module_r}" length="${top_module_h}" />
      </geometry>
    </collision>

    <visual name='top_plate_visual'>
      <origin xyz="0.0 0 0.1" rpy=" 0 0 0"/>
      <geometry>
        <cylinder radius="${top_module_r}" length="${top_module_h}" />
      </geometry>
    </visual>

  </link>
  
  <!--
  #################################################
        link = left_wheel
  #################################################
  -->
  
  <link name='left_wheel'>
    <pose>0 0 0 0 0 0</pose>

    <inertial>
      <mass value="5.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name='left_wheel_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <cylinder radius="0.05" length="0.05" />
      </geometry>
    </collision>

    <visual name='left_wheel_visual'>
      <origin xyz="0 0 0" rpy="-1.57 0 0"/>
      <geometry>
        <mesh filename="package://my_robot/meshes/wheel.stl" scale="0.0015 0.0015 0.0015" />
      </geometry>
    </visual>
  </link>
  
  <!--
  #################################################
        link = right_wheel
  #################################################
  -->
  
  <link name='right_wheel'>
    <pose>0 0 0 0 0 0</pose>

    <inertial>
      <mass value="5.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name='right_wheel_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <cylinder radius="0.05" length="0.05" />
      </geometry>
    </collision>

    <visual name='right_wheel_visual'>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://my_robot/meshes/wheel.stl" scale="0.0015 0.0015 0.0015" />
      </geometry>
    </visual>
  </link>

  <!--
  #################################################
        link = hokuyo
  #################################################
  -->
  
  <link name='hokuyo'>
    <pose>0 0 0 0 0 0</pose>

    <inertial>
      <mass value="1e-5"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision>
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <box size="0.1 0.1 0.1" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <mesh filename="package://my_robot/meshes/hokuyo.dae" />
      </geometry>
    </visual>
  </link>

  <!--
  #################################################
        link = rgbd_camera_link
  #################################################
  -->
  
  <link name="camera_link_optical">
  </link>
  
  <link name='rgbd_camera_link'>
    <pose>0 0 0 0 0 0</pose>

    <inertial>
      <mass value="0.2"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision>
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <box size="${camera_w} ${camera_l} ${camera_h}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${camera_w} ${camera_l} ${camera_h}" />
      </geometry>
    </visual>
  </link>

</robot>
